name: "Create Webhook"
description: "Create a webhook config to a GitHub repository"
author: "Karen Almog"
inputs:
  repository:
    required: false
    description: "The repository in which to install the webhook. Defaults to the repository running the action."

  github_token:
    required: false
    description: "The github token to use for the destination repository."

  webhook_name:
    required: false
    description: "The name of the webhook object in the github repository."
    default: web

  webhook_url:
    required: true
    description: "The URL of the server that will receive the webhook POST requests."

  content_type:
    required: true
    description: "The type of payload delivered in the body. Can be json or form. Default is json."
    default: "json"

  webhook_secret:
    required: true
    description: "The secret used to authenticate with the webhook API."

runs:
  using: "composite"
  steps:
    - name: install jsonnet
      uses: kobtea/setup-jsonnet-action@v1

    - name: jsonnet-render
      id: jsonnet-render
      uses: alexdglover/jsonnet-render@v2
      with:
        file: ./webhook.jsonnet
        output_file: webhook.json
        params: webhook_name=${{ inputs.webhook_name }} webhook_url=${{ inputs.webhook_url }} webhook_secret=${{ inputs.webhook_secret }} content_type=${{ inputs.content_type}}

    - name: debug jsonnet
      shell: bash
      run: cat webhook.json
