name: "Test webhook config"
on:
  push:
  pull_request:

jobs:
  local_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./
      - name: "run locally"
        uses: ./
        with:
          webhook_url: http://localhost:2020
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          repository: mygh_user/testrepo
          github_token: ${{ secrets.WEBHOOK_REPO_GITHUB_TOKEN }}
